all: install

install: install-tensorflow install-gym install-atari

install-atari:
	python3 -m pip install --user --upgrade pip
	python3 -m pip install --user --upgrade atari-py

install-gym:
	python3 -m pip install --user --upgrade pip
	python3 -m pip install --user --upgrade gym


install-tensorflow:
	python3 -m pip install --user --upgrade pip
	python3 -m pip install --user --upgrade tensorflow
#	python3 -m pip install --user --upgrade tensorflow-gpu
